brew "stow"

# Git
brew "git"
brew "gh"

# Password Manager
cask "1password"
cask "1password-cli"

# Utility
cask "rectangle-pro"  # Window manager
cask "the-unarchiver" # archiver

# Web browser
cask "google-chrome"
cask "firefox"
cask "zen-browser"
cask "arc"

# Terminal
brew "starship"
cask "ghostty"

# Font
cask "font-plemol-jp"
cask "font-plemol-jp-hs"
cask "font-plemol-jp-nf"

# Editor
cask "visual-studio-code"
vscode "vscodevim.vim"
vscode "yzhang.markdown-all-in-one"
