brew "stow"

# Git
brew "git"

# Password Manager
cask "1password"
cask "1password-cli"

# Web browser
cask "google-chrome"
cask "firefox"
cask "zen-browser"

# Terminal
cask "ghostty"

# Font
cask "font-plemol-jp"
cask "font-plemol-jp-hs"
cask "font-plemol-jp-nf"
