[".local/bin/lua-language-server"]
# type = "archive-file"
# url = "https://github.com/LuaLS/lua-language-server/releases/download/3.13.5/lua-language-server-3.13.5-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
# path = "bin/lua-language-server"
type = "archive"
url = "https://github.com/LuaLS/lua-language-server/releases/download/3.13.5/lua-language-server-3.13.5-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"

