secrets:
  GITHUB_PERSONAL_ACCESS_TOKEN:
    vault: h5f5iufx5d7ls5jmcjocwueexq
    item: "GitHub"
    fields:
      - label: token

  # その他の例
  # OPENAI_API_KEY:
  #   item: "OpenAI API Key"
  #   fields:
  #     - label: credential
