tap "homebrew/bundle"

brew "eza"
brew "fzf"
brew "ghq"
brew "git"
brew "mas"
brew "mise"
brew "nvim"
brew "zoxide"
brew "zsh-completions"

cask "1password"
cask "1password-cli"
cask "alacritty"
cask "arc"
cask "font-udev-gothic"
cask "font-udev-gothic-nf"
cask "karabiner-elements"
cask "rectangle-pro"
cask "visual-studio-code"
