[tools]
#===================================================================================================
# NodeJS
#===================================================================================================
node = "24"
"npm:@anthropic-ai/claude-code" = "latest"

#===================================================================================================
# Lua
#===================================================================================================
lua-language-server = "latest"
