[tools]
go = "latest"
golangci-lint = "latest"
node = "latest"
pnpm = "latest"
biome = "latest"
"npm:typescript" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
python = "latest"
uv = "latest"
"pipx:aws-mfa-v2" = "latest"

[settings]

[settings.pipx]
uvx = true

