[tools]
#===================================================================================================
# NodeJS
#===================================================================================================
node = "24"
"npm:@anthropic-ai/claude-code" = "latest"

#===================================================================================================
# Go
#===================================================================================================
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest"

#===================================================================================================
# Python
#===================================================================================================
python = "latest"
uv = "latest"
"pipx:aws-mfa-v2" = "latest"

#===================================================================================================
# Lua
#===================================================================================================
lua-language-server = "latest"
