[tools]
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:gh" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:rossmacarthur/sheldon" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:tmux/tmux-builds" = "latest"

[tasks.up]
description = "Homebrew と mise をまとめて更新"
run = [
  "brew update",
  "brew upgrade",
  "brew cleanup",
  "mise self-update --yes",
  "mise upgrade",
  "mise prune --yes",
]
