[tools]
# Python
python = "latest"
uv = "latest"
"pipx:aws-mfa-v2" = "latest"

# Node
bun = "latest"
node = "latest"
pnpm = "latest"
biome = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"

# Lua
lua-language-server = "latest"
