return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  build = ":TSUpdate",
  opts = {
    install_dir = vim.fn.stdpath("data") .. "/site",
    ensure_installed = {
      "bash",
      "c",
      "c_sharp",
      "comment",
      "css",
      "csv",
      "dart",
      "diff",
      "editorconfig",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "gomod",
      "gosum",
      "gotmpl",
      "gowork",
      "graphql",
      "html",
      "http",
      "ini",
      "java",
      "javadoc",
      "javascript",
      "jq",
      "jsdoc",
      "json",
      "json5",
      "jsonnet",
      "jsx",
      "kotlin",
      "latex",
      "lua",
      "luadoc",
      "luap",
      "make",
      "markdown",
      "markdown_inline",
      "mermaid",
      "nginx",
      "php",
      "php_only",
      "phpdoc",
      "prisma",
      "proto",
      "printf",
      "python",
      "query",
      "regex",
      "ruby",
      "rust",
      "scala",
      "scss",
      "sql",
      "svelte",
      "swift",
      "terraform",
      "tmux",
      "toml",
      "tsv",
      "tsx",
      "typescript",
      "typespec",
      "typst",
      "vim",
      "vimdoc",
      "vue",
      "xml",
      "yaml",
      "zsh",
    },
  },
  config = function(_, opts)
    local TS = require("nvim-treesitter")
    TS.install(opts.ensure_installed) 

    -- Highlighting
    vim.api.nvim_create_autocmd("FileType", {
      pattern = opts.ensure_installed,
      callback = function() vim.treesitter.start() end,
    })

    -- Folds
    vim.wo[0][0].foldexpr = "v:lua.vim.treesitter.foldexpr()"
    vim.wo[0][0].foldmethod = "expr"

    -- Indentation
    vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
  end,
}
