set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Plugins
set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.local/share/tmux/plugins"

set -g @plugin "tmux-plugins/tpm"            # プラグインマネージャー
set -g @plugin "tmux-plugins/tmux-sensible"  # 便利設定詰め合わせ
set -g @plugin "tmux-plugins/tmux-resurrect" # セッションの状態を手動で保存・復元する
set -g @plugin "tmux-plugins/tmux-continuum" # セッションの状態を自動で保存・復元する (require: tmux-resurrect)
set -g @plugin "catppuccin/tmux"             # Theme

run "~/.local/share/tmux/plugins/tpm/tpm"
