# 設定を反映する
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reload config."

# Prefixキーの変更
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# ペインを水平分割するキーバインドを変更する
unbind "
bind - split-window -v

# ペインを垂直分割するキーバインドを変更する
unbind %
bind | split-window -h

# ステータスバーを上に表示する
set-option -g status-position top

