require("plugins.snacks")
require("plugins.catppuccin")
require("plugins.nvim-treesitter")
require("plugins.nvim-treesitter-textobjects")
require("plugins.nvim-tmux-navigation")
require("plugins.gitsigns")
require("plugins.sidekick")
require("plugins.incline")
